FROM rootventures/train-dreambooth:latest

RUN --mount=type=cache,target=/var/cache/apt \
  sudo apt-get update && \
  DEBIAN_FRONTEND=noninteractive sudo apt-get install -y gcc glibc && \
  pip3 install --no-cache-dir --upgrade sagemaker-training && \
  sudo apt-get remove -y gcc glibc && \
  sudo rm -rf /var/lib/apt/lists/*

ENV ACCELERATE_MIXED_PRECISION bf16
ENV INSTANCE_TYPE ml.p4d.24xlarge
