on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          swap-storage: true
          large-packages: true

      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.10"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::630351220487:role/Github_Dreambooth
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (SageMaker)
        id: sm_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/train-dreambooth-sagemaker
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker meta (RunPod)
        id: rp_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            rootventures/train-dreambooth-runpod
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Clean up space
        run: docker system prune -af

      - name: Build and push (SageMaker)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/Dockerfile.sagemaker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.sm_meta.outputs.tags }}
          labels: ${{ steps.sm_meta.outputs.labels }}
          cache-from: type=gha,compression=zstd
          cache-to: type=gha,mode=min,oci-mediatypes=true,compression=zstd
          outputs: "type=registry,oci-mediatypes=true,compression=zstd,compression-level=3"

      - name: Build and push (RunPod)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/Dockerfile.runpod
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.rp_meta.outputs.tags }}
          labels: ${{ steps.rp_meta.outputs.labels }}
          cache-from: type=gha,compression=zstd
          cache-to: type=gha,mode=min,oci-mediatypes=true,compression=zstd
          outputs: "type=registry,oci-mediatypes=true" # compression=zstd,compression-level=3n
